[package]
name = "bdk-rpc-client"
version = "0.1.0"
edition = "2024"

[dependencies]
corepc-types = { version = "0.10.1", features = ["default"]}
jsonrpc = { version = "0.18.0", features = ["simple_http", "simple_tcp", "minreq_http", "simple_uds", "proxy"] }

